export const ADD_TO_CART = 'ADD_ITEM';
export const REMOVE_FROM_CART = 'REMOVE_ITEM';
export const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT';
export const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT';
export const SET_COUNT_ZERO = 'SET_COUNT_ZERO';